### ISSUE TITLE
Stack / Heap memory limit

### ISSUE THREAD

**Issue by kaizerpwn** [oscar-broman/samp-translate#7]
Hello, 

I translated about 1k messages and encountered this error when I tried to extend MAX_TRANSLATED_STRINGS to 2048 from 1024.

![code](https://github.com/oscar-broman/samp-translate/assets/70588174/2a78f870-b2ef-418a-8e56-c5fd82d72401)
![Screenshot_5](https://github.com/oscar-broman/samp-translate/assets/70588174/011c0736-e6a5-4675-bd1c-ae8fe652ab59)

The problem is that I can't store all translation stuff in one array, is there any suggestion on how this can be solved?

**Comment by oscar-broman** [comment]
You need to increase the heap size. That can be done using `#pragma dynamic`.

**Comment by kaizerpwn** [comment]
Yep, that solved the problem, btw. I use YSI so I defined a constant with the name "DYNAMIC_MEMORY" 
 (https://github.com/pawn-lang/YSI-Includes/blob/1be9840c87c13b6545d0c91c623ec541b051e452/YSI_Coding/y_malloc/faqs.md?plain=1#L29)
 
 Thanks for your assistance.
